CREATE DATABASE crane;
CREATE TABLE User (
    username VARCHAR(20) NOT NULL,
    email VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL,
    PRIMARY KEY (username)
);

CREATE USER 'deleteRole'@'192.168.1.1__' IDENTIFIED BY 'INTRODUCEPASSWORD';
GRANT SELECT, DELETE ON crane.user TO 'deleteRole'@'192.168.1.1__';

CREATE USER 'insertRole'@'ip-máquina' IDENTIFIED BY 'INTRODUCEPASSWORD';
GRANT INSERT ON crane.user TO 'insertRole'@'`192.168.1.1__';
